spring:
  application:
    name: toastit

  profiles:
    active: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#  web:
#    resources:
#      add-mappings: false  # 정적 리소스 매핑을 비활성화하는 설정

  mongodb:
    embedded:
      version: 4.0.21

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 개발 중 캐시 비활성화

  datasource:
    url: jdbc:mysql://15.164.25.150:3306/toastitdb
    username: root
    password: root@20240801
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 10MB

cloud:
  aws:
    credentials:
      instance-profile: false
      accessKey:
      secretKey:
    region:
      static: ap-northeast-2
    s3:
      bucket: toastitbucket