spring:
  datasource:
    url: jdbc:mysql://15.164.25.150:3306/toastitdb
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 10MB
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DEV_GAMIL_USERNAME}
    password: ${DEV_GAMIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

cloud:
  aws:
    credentials:
      instance-profile: false
      accessKey:
      secretKey:

    s3:
      bucket: toastitbucket

    region:
      static: ap-northeast-2
      auto: false

file:
  cloudfront-path: ${DEV_FILE_PATH}

jwt:
  accessSecret: ${DEV_JWT_ACCESS_SECRET}
  refreshSecret: ${DEV_JWT_REFRESH_SECRET}
  accessTokenExpire: ${DEV_JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${DEV_JWT_REFRESH_EXPIRE}