spring:
    application:
        name: toastit

    profiles:
      active: local

    jpa:
      show-sql: true
      database: mysql
      hibernate:
        ddl-auto: create
    web:
      resources:
        add-mappings: false