spring:
  application:
    name: toastit

  profiles:
    active: local, oauth

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  #  web:
  #    resources:
  #      add-mappings: false  # 정적 리소스 매핑을 비활성화하는 설정

  mongodb:
    embedded:
      version: 4.0.21

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 개발 중 캐시 비활성화

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 10MB

api:
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}