spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_MYSQL_URL}
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}

    mongodb:
      host: ${DEV_MONGO_HOST}
      port: ${DEV_MONGO_PORT}
      username: ${DEV_MONGO_USERNAME}
      password: ${DEV_MONGO_PASSWORD}
      database: ${DEV_MONGO_DATABASE}
      authentication-database: ${DEV_MONGO_AUTH}
      uri: ${DEV_MONGO_URI}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DEV_GMAIL_USERNAME}
    password: ${DEV_GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

cloud:
  aws:
    credentials:
      instance-profile: false
      accessKey: ${DEV_AWS_ACCESS_KEY}
      secretKey: ${DEV_AWS_SECRET_KEY}

    s3:
      bucket: ${DEV_AWS_BUCKET_NAME}

    region:
      static: ${DEV_AWS_STATIC_NAME}
      auto: false

file:
# cloudfront-path: ${DEV_FILE_PATH}

image:
  default-profile-path: ${DEV_USER_PROFILE_PATH}

jwt:
  accessSecret: ${DEV_JWT_ACCESS_SECRET}
  refreshSecret: ${DEV_JWT_REFRESH_SECRET}
  accessTokenExpire: ${DEV_JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${DEV_JWT_REFRESH_EXPIRE}

google:
  maps:
    api:
      key: ${DEV_GOOGLE_MAP_API_KEY}

  geocoding:
    api:
      key: ${DEV_GOOGLE_GEOCODING_API_KEY}