### expiredToken
GET http://localhost:8080/test/expired-token

### unsupportedToken
GET http://localhost:8080/test/unsupported-token

### invalidToken
GET http://localhost:8080/test/invalid-token

### illegal-argument
GET http://localhost:8080/test/illegal-argument

### internalError
GET http://localhost:8080/test/internal-error
