name: Discord Notifications

on:
  # pr - opened, synchronize, reopened, closed 이벤트 발생 시 discord 알림
  pull_request:
    types: [opened]

  # push - main 브랜치에 push 이벤트 발생 시 discord 알림
  push:
    branches:
      - main

jobs:
  discordNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Discord Github Notification
        uses: Aleph-Kim/discord-github-notification@v1.2.1
        with:
          # GitHub Secret Key 탭에 저장한 discord webhook url
          discord-webhook-url: ${{ secrets.WEBHOOK_FOR_DISCORD }}